# Generated by Django 2.1 on 2018-10-15 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectureID', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('professor', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LectureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LecturePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(default='', upload_to='')),
                ('image2', models.ImageField(default='', upload_to='')),
                ('image3', models.ImageField(default='', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('realname', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phoneNum', models.CharField(max_length=20)),
                ('image', models.ImageField(default='media/default_image.jpeg', upload_to='media/original')),
            ],
        ),
        migrations.AddField(
            model_name='lecturepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khunect.User'),
        ),
        migrations.AddField(
            model_name='lecturepost',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khunect.Lecture'),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khunect.LecturePost'),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khunect.User'),
        ),
    ]
